# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0784022cd43602b3cfbb077cea36a3de970eab893fdacce2a9e832a0adf01db263d21f0dd8a993c285a4b45556d8397e681b2859c267e0c7b284fc132ff76a70

test:
  secret_key_base: 2e6b9c714494d6a64ad3ea41023520d297f9598520fef6d58d4bfe61338c7d13afda865691d195d17c1c9e230247be52532207724dd5ac7a2e8aa26e4900184f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
